

services:
  frontend:
    container_name: within_front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app:rw
      - /app/node_modules
    networks:
      - within-networks

networks:
  within-networks:
    external: true
