version: "3.9"

services:
  frontend:
    container_name: patienceBank_front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # ★ここをWSLパスに変える（自分の実パスに合わせて）
      - /mnt/c/GitHub/patience-bank/patienceBank-front:/app:rw
      - /app/node_modules
    networks:
      - patienceBank-networks

networks:
  patienceBank-networks:
    external: true
